import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme_providers/shadcn-theme-provider"

import { createTheme, CssBaseline } from "@mui/material"
import { MuiThemeProvider } from "@/components/theme_providers/material-ui-theme-provider"

const notoSans = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={notoSans.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <MuiThemeProvider>
            <CssBaseline />
            {children}
          </MuiThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
