import { Roboto } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme_providers/shadcn-theme-provider"

import { CssBaseline } from "@mui/material"
import { MuiThemeProvider } from "@/components/theme_providers/material-ui-theme-provider"
import { UserDetailsProvider } from "@/context/userDetails"
import { Toaster } from "react-hot-toast"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <MuiThemeProvider>
            <UserDetailsProvider>
              <CssBaseline />
              <Toaster />
              {children}
              <Toaster richColors />
            </UserDetailsProvider>
          </MuiThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
